namespace: "ibm"
name: "cloud"
version: "1.0.0"
readme: "README.md"
authors:
    - "Kavya Handadi"
    - "Mujeeb Rahman"
    - "Harini Kantareddy"
    - "Umar Ali"
description: "Ansible modules collection for IBM-Cloud."
license_file: LICENSE
tags: [ibm, cloud]
repository: "https://github.com/ansible-collections/ibm.cloud"
homepage: "https://github.com/ansible-collections/ibm.cloud"

issues: "https://github.com/ansible-collections/ibm.cloud/issues"
