namespace: "ibm"
name: "cloud"
version: "0.0.1-beta0"
readme: "README.md"
authors:
    - "Mujeebur Rahman"
    - "Harini Kantareddy"
    - "Kavya Handadi"
description: "Ansible modules collection for IBM-Cloud."
license_file: LICENSE
tags: [ibm-cloud, ibm, cloud]
repository: "https://github.com/ansible-collections/ibm.cloud"
homepage: "https://github.com/ansible-collections/ibm.cloud"

issues: "https://github.com/ansible-collections/ibm.cloud/issues"
